lib/nostrum/api.ex

content needs to be String not Map

Fix create_message when using an embed

---

lib/nostrum/shard/dispatch.ex

Fix :unavailable key not found in :GUILD_DELETE p

---

lib/nostrum/shard/dispatch.ex

Changes it so that guild_id in cached channels is not nil.

Include proper channel caching

---

lib/nostrum/consumer.ex
lib/nostrum/shard/dispatch.ex

Add missing events

---

examples/cache.ex

Just a simple example of how to use the Cache system.

Add an example for using Cache

---

lib/nostrum/api.ex
lib/nostrum/struct/guild/member.ex

Similar to the other PRs. Name changes, typespec cleanups, struct updates, etc.

HTTP API Cleanup for Member struct

---

lib/nostrum/api.ex
lib/nostrum/struct/guild/role.ex
test/nostrum/struct/guild/role_test.exs

Fixes mainly for updating the struct, updating documentation, and fixing decoding errors.

HTTP API Cleanup for Role struct

---

README.md

Because nostrum can't be semi-professional without one of these things!
🙃 🙃 🙃 🙃 🙃

Added Travis CI Badge to root README

---

lib/nostrum/api.ex
lib/nostrum/struct/embed.ex
lib/nostrum/struct/emoji.ex
lib/nostrum/struct/guild/member.ex
lib/nostrum/struct/snowflake.ex
lib/nostrum/struct/user.ex
test/nostrum/struct/embed_test.exs
test/nostrum/struct/emoji_test.exs
test/nostrum/struct/guild/member_test.exs
test/nostrum/struct/snowflake_test.exs
test/nostrum/struct/user_test.exs

This PR focuses on fixing struct-specific features that should have been or should now be changed due to decisions we've made in the most recent PRs. Many of these include corrections to fix inconsistencies. Pretty much a fast-forward PR. This includes:
* Adding mentions to specific structs.
* Improving documentation to match our current standard.
* Improving typespecs where possible.
* Improving function names where possible.
* Creating and improving tests and doctests.
I'll hit API specific features in a future PR.

Fast Forwarding Previous Struct Work

---

README.md

Added a Getting Help section so users know where to find help.
~~Also added a discord badge because memes.~~

Added discord badge and "Getting Help" section

---

lib/nostrum/consumer.ex
lib/nostrum/shard/session.ex
lib/nostrum/struct/ws_state.ex

Change the WS state from a map to a struct, fixes #65

---

docs/static/State.md
examples/cache.ex
lib/nostrum/api.ex
lib/nostrum/cache/channel_cache.ex
lib/nostrum/cache/guild/guild_register.ex
lib/nostrum/cache/guild/guild_server.ex
lib/nostrum/cache/guild_cache.ex
lib/nostrum/cache/mapping/channel_guild.ex
lib/nostrum/cache/mapping/guild_shard.ex
lib/nostrum/cache/mapping/shard_pid_num.ex
lib/nostrum/cache/me.ex
lib/nostrum/shard/dispatch.ex
lib/nostrum/struct/guild.ex
lib/nostrum/util.ex
test/nostrum/cache/guild_cache_test.exs

- Fix guild struct decoding values.
- Fix guild-related API endpoints not decoding to the correct types.
- Remove id-indexing in roles, members, channels of the guild struct.

Guild Struct and API Fixes

---

.travis.yml

* Fixes some formatting errors that are important for our travis builds.

Updated Travis to use Elixir 1.6.5

---

lib/nostrum/constants.ex
lib/nostrum/struct/emoji.ex

* We should add this because it makes getting an emoji's image URL less cumbersome.

Added `image_url/1` to Emoji module

---

lib/nostrum/struct/guild/member.ex
lib/nostrum/struct/permission.ex
test/nostrum/struct/guild/member_test.exs
test/nostrum/struct/permission_test.exs

This PR adds in some well-needed permission utility functions.
* Added in a Permission module for working with permissions.
* Added in `guild_permissions/2` to the Member module for getting a guild member's perms.
More to go, as this is WIP.

Permission Utility Functions

---

lib/nostrum/constants.ex
lib/nostrum/struct/snowflake.ex
test/nostrum/struct/snowflake_test.exs

This introduces the feature request from #89.
I've also cleaned up the Snowflake module a little bit while I was here.

Added `Snowflake.from_datetime/1`

---

lib/nostrum/cache/guild/guild_server.ex

This fixes the #91 issue.
I've also included some extra cleanups while I was here.

Fix Members not updating new `nil` fields in cache

---

lib/nostrum/struct/guild/member.ex
lib/nostrum/struct/permission.ex
test/nostrum/struct/guild/member_test.exs

For reference, these were found using:

Fix old code examples & permission checking using `Enum.find`

---

lib/nostrum/struct/embed.ex

Make nil the default value for icon_url for put_footer/3
Let's be real, icon_url is going to be nil most of the time.

Default value for icon_url

---

lib/nostrum/cache/presence_cache.ex

Super small fix to mitigate the dialyzer warnings/errors.

Dialyzer Fix for `PresenceCache`

---

README.md
examples/event_consumer.ex
lib/nostrum/consumer.ex
lib/nostrum/dummy.ex
lib/nostrum/shard/dispatch.ex
lib/nostrum/struct/event/message_delete_bulk.ex
test/nostrum/shard/dispatch_test.exs
test/stubs.ex

Introduces a Gateway struct for representing Message Delete Bulk events.

Gateway Struct for Message Delete Bulk Event

---

lib/nostrum/shard/session.ex

Fix typos related to timer cancellation.

---

lib/nostrum/shard/session.ex

https://discordapp.com/channels/81384788765712384/381889573426429952/611284767714967564
https://gist.github.com/Andris0/51cc290cd921ef12f9c66da80a0e90e5

Reset `heartbeat_ack` on WS reconnect.

---

docs/static/Intro.md

Link bolt as a "more complex bot".

---

lib/nostrum/api.ex

This adds an method to modify current nickname in that guild.

add Modify Current User Nick

---

README.md
lib/nostrum/api.ex
lib/nostrum/constants.ex
lib/nostrum/struct/channel.ex
lib/nostrum/struct/embed.ex
lib/nostrum/struct/guild/audit_log_entry.ex
lib/nostrum/struct/message.ex
lib/nostrum/struct/message/activity.ex

Replace discordapp.com with discord.com (except for cdn.discordapp.com)
Fixes: https://github.com/Kraigie/nostrum/issues/170

discordapp -> discord

---

docs/static/Consumers.md
examples/cache.ex

The title is indeed accurate, can confirm, I witnessed it.

Updated `cache.ex` example

---

lib/nostrum/application.ex
lib/nostrum/dummy.ex
lib/nostrum/shard/supervisor.ex
lib/nostrum/util.ex

+ A minor cleanup for Application and Dummy testing modules
+ Specific `raise` case for fetching gateway info with invalid token (first authenticated API request)
+ Integrity check for configured shard count

Application and adjacent module cleanup

---

docs/static/Gateway Intents.md
lib/nostrum/shard/intents.ex
test/nostrum/shard/intents_test.exs

Add convenience keys for gateway_intents config

---

lib/nostrum/api.ex

Revert "fix: status passed as :atom is ignored"

---

lib/nostrum/struct/guild/member.ex
test/nostrum/struct/guild/member_test.exs

Revert "Fix `guild_permissions` type failure."

---

lib/nostrum/struct/voice_state.ex
lib/nostrum/voice.ex
lib/nostrum/voice/audio.ex
lib/nostrum/voice/session.ex

Adds options to play function to select if you want real-time processing (performance tradeoffs), selecting a different start position, and selecting a custom duration.

Add options to Nostrum.Voice.play.

---

.github/workflows/docs.yml
.github/workflows/test_and_lint.yml

`actions/setup-elixir` has been archived.
Closes #237.

Migrate CI to `erlef/setup-beam` action.

---

.github/dependabot.yml

Up to one weekly PR with a dependency update.

Add automated dependency updates.

---

lib/nostrum/api.ex

Adds API functions for interacting with the following endpoints:
- https://discord.com/developers/docs/interactions/slash-commands#bulk-overwrite-global-application-commands
- https://discord.com/developers/docs/interactions/slash-commands#bulk-overwrite-guild-application-commands

Add functions for bulk overwriting application commands

---

lib/nostrum/shard/session.ex

I suppose that some days, the door just gets slammed shut.

Handle WS close without a reason.

---

lib/nostrum/shard/dispatch.ex
lib/nostrum/struct/event/voice_server_update.ex
lib/nostrum/struct/event/voice_state.ex
lib/nostrum/struct/voice_state.ex
lib/nostrum/voice/session.ex

Keep self_deaf and self_mute for reconnects.
Fix to_struct for voice event structs.

Maintain status of self-deaf and self-mute for bot. 

---

lib/nostrum/voice.ex
lib/nostrum/voice/audio.ex
lib/nostrum/voice/event.ex

Add RTP listening to Voice API

Voice listen

---

README.md

Take it from the third language English guy.

Reword some parts of the README, link documentation.

---

lib/nostrum/cache/guild_cache.ex
lib/nostrum/shard/dispatch.ex

Thanks to The Major for reporting these.

Fix gateway payload key types.

---

lib/nostrum/cache/guild_cache.ex
lib/nostrum/shard/dispatch.ex

Thanks to snapcase for reporting this issue.

Use proper key type for channel update events.

---

lib/nostrum/cache/guild_cache.ex

Small fix to trim the heavy voice state update which was lost during the move to ETS guild cache. Dropping both `"member"` and `:member` keys from the map in case Discord later decides to normalize and return `member` as an atom instead of a string.

Trim voice state updates with correct key(s)

---

lib/nostrum/api.ex
lib/nostrum/api/base.ex
lib/nostrum/api/ratelimiter.ex

Create query string from params if present in options and convert options to map if it's a keyword list.

Gun url params

---

lib/nostrum/struct/application_command_interaction_data_resolved.ex

This allows Nostrum to support context menu commands on messages.
tested it on my bot to confirm that it works.

add messages field to application data resolved

---

lib/nostrum/cache/guild_cache.ex

This is caused by the relevant intents missing. Discord will still send
us updates about or own user.
Fixes #293.

Fix crash on GUILD_MEMBER_UPDATE with uncached guild.

---

lib/nostrum/api.ex
lib/nostrum/struct/application_command_interaction_data.ex
lib/nostrum/struct/event/message_reaction_add.ex
lib/nostrum/struct/event/partial_application.ex
lib/nostrum/struct/event/ready.ex
lib/nostrum/voice/audio.ex

Two missing warnings are not fixed as part of this PR, there's missing
struct definitions for the user connection and guild integration type.

Fix dialyzer complaints on master.

---

docs/static/Intro.md
docs/static/Voice.md
lib/nostrum/application.ex
lib/nostrum/voice.ex
lib/nostrum/voice/audio.ex

Support playing livestream audio with streamlink

---

lib/nostrum/cache/guild_cache.ex

Return guild_id on member update.

---

lib/nostrum/application.ex
lib/nostrum/cache/cache_supervisor.ex
lib/nostrum/cache/channel_cache.ex
lib/nostrum/cache/channel_cache/ets.ex
test/nostrum/cache/channel_cache_test.exs

Work in progress PR resolving issue #355.
We made the adjustments to transform ChannelCache to be pluggable just as asked and created tests for this.
The PR is in Work in Progress because we need to update the Docs on the files created.
:)

Converting ChannelCache to be pluggable

---

lib/nostrum/application.ex
lib/nostrum/cache/cache_supervisor.ex
lib/nostrum/cache/guild_cache.ex
lib/nostrum/cache/user_cache.ex
lib/nostrum/cache/user_cache/ets.ex
test/nostrum/cache/user_cache_test.exs

Modified the `UserCache` to use a Supervisor behaviour, and simplified the compile_env call in `GuildCache`.
Closes #354

Modify UserCache to use Supervisor

---

lib/nostrum/cache/guild_cache.ex
lib/nostrum/cache/guild_cache/ets.ex
test/nostrum/cache/guild_cache_test.exs

I got no issues with the typespecs I changed, but this is the first time I have worked with them before so do double check I got those right.
Closes #376 
Thanks!

Fix GuildCache.ETS not including guild_id in role_create and role_update methods.

---

lib/nostrum/struct/channel.ex
lib/nostrum/struct/event/channel_pins_update.ex
lib/nostrum/struct/event/voice_state.ex
lib/nostrum/struct/guild.ex
lib/nostrum/struct/guild/member.ex
lib/nostrum/struct/guild/scheduled_event.ex
lib/nostrum/util.ex

Adds `maybe_to_datetime/1` to `Util` for doing so.

Convert ISO8601 timestamps to `DateTime`

---

lib/nostrum/struct/application_command_interaction_data_option.ex
lib/nostrum/struct/event/guild_ban_add.ex
lib/nostrum/struct/event/guild_ban_remove.ex
lib/nostrum/struct/event/guild_integrations_update.ex
lib/nostrum/struct/event/message_reaction_add.ex
lib/nostrum/struct/event/message_reaction_remove.ex
lib/nostrum/struct/event/message_reaction_remove_all.ex
lib/nostrum/struct/event/message_reaction_remove_emoji.ex
lib/nostrum/struct/event/typing_start.ex
lib/nostrum/struct/message.ex

Two PRs ago I missed the timestamp field in `TypingStart` and two fields in `Message`. This addresses that.
This also now addresses #384 because I forgot I had an open PR

Add the three time fields I missed earlier

---

lib/nostrum/api.ex

Add bangified versions of `create_interaction_response`, `edit_interaction_response`, `delete_interaction_response`, `create_followup_message` and `delete_followup_message`

Add bangified interaction fns

---

docs/static/Voice.md
lib/nostrum/voice/audio.ex

Streamlink version 3.x.x works with more urls out of the box. Removing the extra step of using `youtube-dl` to grab the raw stream url dramatically improves startup time for `play/4` and allows the user to pass any url directly to streamlink, while docs show how to fetch the "raw stream url" using `youtube-dl` if needed. 
Additionally fixing a bug with stateful raw audio source which I caught coincidentally because I didn't have a proper way to test it before and I don't think anyone has used it yet.
Up-to-date version of streamlink can be installed with `pip install --upgrade streamlink` (3.1.1 is current newest and recommended).
Testing can be done with these helper funcs
```elixir
def join_voice, do: Voice.join_channel(@guild_id, @channel_id)
def leave_voice, do: …
```

Streamline Streamlink

---

lib/nostrum/voice.ex
lib/nostrum/voice/audio.ex
lib/nostrum/voice/opus.ex
lib/nostrum/voice/ports.ex

Initial pass at adding functionality for listening on voice channels

Ogg Opus encapsulation for voice listening

---

lib/nostrum/api.ex

Remove buggy and now unused code that was causing some issues when moving from .5 rc to latest
Make request_multipart useful, removing duplicate code to make multipart and file handling easier
Additionally:
- fix spec for request_multipart
- fix bug where execute_webhook and edit_webhook message wasn’t casting to `Message` struct
- make internal function private
- silently handle combining `:embed` and `:embeds` similarly to `:file` and `:files`
- make file form name `files[n]` where `n` begins at 0 according to most recent docs
- support files for all applicable message editing functions

Declutter multipart functionality in api.

---

lib/nostrum/voice.ex

Make listening more ergonomic. Breaking change. Auto parse RTP header and opus when listening. Optionally return raw RTP packet. Change extract function to expect full RTP packet vs just payload.
For 0.6.0 release. 
did this on me fone🤳

Make breaking change to voice listening

---

examples/audio_player_example.ex

Same thing needs to be done to other examples to be compatible with v10 gateway

Update audio example to use application commands

---

lib/nostrum/api/bucket.ex
lib/nostrum/api/ratelimiter.ex

PR to fix the rate limit issue we had with reactions going to the wrong bucket

put reactions in their own rate limit bucket

---

lib/nostrum/struct/application_command_interaction_data_resolved.ex

I think this adds attachments, I have been using it locally for a while

Attachments

---

lib/nostrum/consumer.ex
lib/nostrum/shard/dispatch.ex

Adds the [audit log entry event](https://discord.com/developers/docs/topics/gateway-events#guild-audit-log-entry-create)

Add audit log entry event

---

.formatter.exs
.gitignore
benchmarks/README.md
benchmarks/member_cache_bench.exs
lib/nostrum/cache/channel_cache.ex
mix.exs
mix.lock

Will be used in an upcoming PR.

Add caching benchmarks

---

README.md
appup.ex
guides/intro/intro.md
lib/nostrum/struct/message/poll.ex
lib/nostrum/struct/user.ex
mix.exs

Bump version to 0.9

---

.github/workflows/docs.yml

Via https://github.com/Kraigie/nostrum/actions/runs/9600195520.

Publish docs on Elixir 1.17

---

lib/nostrum/api/ratelimiter.ex

Properly display request originator

---

.github/workflows/test_and_lint.yml

As a GitHub User
I want to have my workflow broken because the distro I use isn't supported by Microsoft anymore
such that I can feel secure and safe thanks to Microsoft's neverending commitment to security

Use latest Ubuntu for workflows
