Kraigie/nostrum

lib/nostrum/api.ex, lib/nostrum/shard/payload.ex, lib/nostrum/shard/session.ex, lib/nostrum/shard/supervisor.ex
Modify the update_status methods to allow a `type` parameter. 
This is to allow users to use the new type statuses that have been implemented (Listening & Watching).
It also works out for future updates to the presence api so long as they just add in a new type, whatever that may be.
=> Implement new statuses

lib/nostrum/cache/channel_cache.ex
The ChannelCache GenServer was incorrectly starting with an empty list as an initial state instead of an empty map. This meant that DM channels could not be properly stored inside of ChannelCache's state.
Changed the initial state of ChannelCache to `%{}` instead of an empty list `[]`
=> Fixed ChannelCache initial state.

lib/nostrum/api.ex
Current version of Nostrum.Api.request_multipart/4 passes incorrectly formatted request body to HTTPoison.request/5 causing Retelimiter to crash with 
```
[error] Task #PID started from Ratelimiter terminating
** (FunctionClauseError) no function clause matching in anonymous fn/2 in :hackney_multipart.len_mp_stream/2
(hackney) /project_path/deps/hackney/src/hackney_multipart.erl:159: anonymous fn({"tts", false}, 1077) in :hackney_multipart.len_mp_stream/2
(stdlib) lists.erl:1263: :lists.foldl/3
(hackney) /project_path/deps/hackney/src/hackney_multipart.erl:159: :hackney_multipart.len_mp_stream/2
(hackney) /project_path/deps/hackney/src/hackney_request.erl:317: :hackney_request.handle_body/4
(hackney) /project_path/deps/hackney/src/hackney_request.erl:81: :hackney_request.perform/2 …
```
=> Fix file upload with Nostrum.Api.create_message/3

lib/nostrum/api.ex
Typespec is incorrect for `create_message/3`
Changed key from "content" to "file_name" in type `message_content`
=> Fix typespec for Nostrum.Api.create_message/3

lib/nostrum/cache/guild/guild_server.ex
Will accept the new partial member into the cache as-is, regardless of existence in the cache beforehand.
=> Resolve #42

lib/nostrum/api.ex, lib/nostrum/cache/me.ex, lib/nostrum/struct/message/attachment.ex, lib/nostrum/struct/snowflake.ex, lib/nostrum/struct/user.ex, lib/nostrum/util.ex, test/nostrum/struct/snowflake_test.exs
This is part one of the the bigger Api correction PR that I'm starting to break apart.
This PR accomplishes the following:
* Ensures the User struct snowflakes are decoded as integers instead of strings
* Fixes User-related functions typespecs, docs, and return values in Api module. Example: certain functions not returning a User struct where specified.
* Adds "bangified" functions for User-related Api calls.
=> Api Correction Part 1: User struct

lib/nostrum/api.ex, lib/nostrum/api/ratelimiter.ex, lib/nostrum/constants.ex, lib/nostrum/struct/emoji.ex, lib/nostrum/util.ex
This PR focuses on correcting the Api by cleaning up the pre-existing structs.
This PR does the following:
1. Cleans up the emoji struct by organizing it. Additionally, it adds more documentation to the Emoji module's elements.
2. Corrects specs in the Api module regarding Emojis.
3. Adds a couple of utility functions in the Emoji module for helping library users use Emojis with the Api.
4. Fixes the Emoji struct assembly process when reading outside data (converting snowflakes, other structs, etc.)
Notes:
1. I think `delete_reaction/4` in the Api does not have a matching name with the corresponding Discord Api endpoint (DELETE USER REACTION). This is a minor problem, but we could try renaming this function to match it with the endpoint name.
2. I added `to_api_name/1` and `to_markdown/1` …
=> Api Correction Part 2: Emojis

lib/nostrum/struct/message/reaction.ex
Small PR for fixing the `to_struct/1` function for the Reaction struct. Also making sure the Reaction struct is organized properly.
=> Api correction for Reaction struct

lib/nostrum/struct/embed.ex, lib/nostrum/struct/embed/author.ex, lib/nostrum/struct/embed/field.ex, lib/nostrum/struct/embed/footer.ex, lib/nostrum/struct/embed/image.ex, lib/nostrum/struct/embed/provider.ex, lib/nostrum/struct/embed/thumbnail.ex, lib/nostrum/struct/embed/video.ex, test/nostrum/struct/embed_test.exs
This PR makes the following changes:
1. Updates the typespecs for Embed fields and its components.
2. Updates the `to_struct/1` functions for each Embed and its components.
3. Implements the Poison.Encoder protocol for each Embed and its components.
=> Cleanup for Embeds and its components

lib/nostrum/cache/user_cache.ex
`Nostrum.Cache.UserCache.get/1` instead of undefined `Nostrum.Cache.User.get/1`.
=> Correction for a doc example.

lib/nostrum/api.ex
Arguments passed to `Nostrum.Api.get_guild_prune/2` were improperly passed to `request` function, causing a malformed request and then failing on parsing the unexpected response content.
```elixir
iex(1)> Nostrum.Api.get_guild_prune(436595814903709706, 1)
** (exit) exited in: GenServer.call(Ratelimiter, {:queue, %{body: 1, headers: [{"content-type", "application/json"}], method: :get, options: [], route: "/guilds/436595814903709706/prune"}, nil}, :infinity)
** (EXIT) an exception was raised:
** (Poison.SyntaxError) Unexpected token at position 0: <
(poison) lib/poison/parser.ex:57: Poison.Parser.parse!/2
(poison) lib/poison.ex:83: Poison.decode!/2
(nostrum) lib/nostrum/api/ratelimiter.ex:168: Nostrum.Api.Ratelimiter.format_response/1
(nostrum) lib/nostrum/api/ratelimiter.ex:55: …
```
=> Fix for `Nostrum.Api.get_guild_prune/2`.

lib/nostrum/cache/channel_cache.ex
~~I decided to go with a more conservative approach and simply make a banged version of the get with Message struct instead of reworking `get` to not have a single keyword arg but idk.~~
Nevermind, went with reworking `get` to take in a simple argument list.
=> Add banged get with Message struct in channel_cache.ex, fixes #53

lib/nostrum/struct/user.ex
This PR adds in two useful functions for working with User structs. These are `avatar_url/2` and `full_name/1`.
* `avatar_url/2` reduces the boilerplate code involved with finding a user's avatar url. It returns the default avatar URL if the user's `:avatar` is `nil`.
* `full_name/1` gives a name to a well known way to identify users on discord.
=> Avatar URL and Full Name Utility Functions for User Module

lib/nostrum/struct/guild.ex
* Issue was that the `:joined_at` documentation was incorrectly stating that this field returned the guild's creation date.
* It's now been corrected to say that `:joined_at` is the bot user's join date for that guild.
=> Fixed typo with `:joined_at` field in Guild struct

lib/nostrum/constants.ex, lib/nostrum/struct/guild.ex, test/nostrum/struct/guild_test.exs
This adds in two functions for the guild module:
* `image_url/2`: For retrieving a guild's icon URL.
* `splash_url/2`: For retrieving a guild's splash URL.
=> Guild Utility Functions

lib/nostrum/api.ex
`:remove` returns
```elixir
{:error, %{message: %{"code" => 0, "message" => "405: Method Not Allowed"}, status_code: 405}}
```
and `:delete` appears to work properly (tested locally on my bot)
=> Fix a typo in `Api.remove_guild_ban/2`.

lib/nostrum/api.ex
Previously `Api.bulk_delete_messages/3` would error (from the Discord API) when given more than 100 messages at once. With this PR, the message list will be chunked into blocks of 100 and sent off to the API chunk by chunk.
=> Allow more than 100 messages in bulk delete

lib/nostrum/struct/overwrite.ex
The Discord API sends the overwrite type as `type`, but `Overwrite` was expecting it to be `name`.
=> Fix incorrect key in `Overwrite` map

README.md
As said in the comment on its right, the token of your bot as a string.
=> Changed token to string

lib/nostrum/cache/channel_cache.ex
After cached guild channel indexing, guilds now hold channels in a map instead of a list and so channel lookup needs to be adjusted accordingly.
=> Fix for `Nostrum.Cache.ChannelCache.lookup/1`.

lib/nostrum/shard/event.ex
Generally it isn't useful to have a constant `[info]  HEARTBEAT_ACK` in the logs, so this makes it be debug level so it can be configured away.
=> Change heartbeat messages to :debug instead of :info

lib/nostrum/consumer.ex
Felt this might be useful to have in the documentation.
=> Document `nil`-able `old_*` states in update events.

lib/nostrum/api.ex, lib/nostrum/util.ex
It is an indirect fix as the issue was in `Nostrum.Util.cast/2`, where it did not expect to receive more than one value in a case where `{:struct, module}` was passed as the `type`. In the case of a call originating from `Nostrum.Api.get_current_user_guilds/1`, `Nostrum.Util.cast/2` reached the last "match all" pattern and failed as it was not intended to handle that scenario.
Behavior before the fix:
```elixir
iex(1)> Nostrum.Api.get_current_user_guilds limit: 1
** (UndefinedFunctionError) function :struct.cast/2 is undefined (module :struct is not available)
:struct.cast([%{icon: "4365a9295ac51200f0a2ae4048dff277", id: "473537126680494111", name: "Curie Dev", owner: false, permissions: 2146958847}], {:struct, Nostrum.Struct.Guild})
(nostrum) lib/nostrum/util.ex:236: Nostrum.Util.cast/2 …
```
=> Fix for Nostrum.Api.get_current_user_guilds/1.

mix.exs
While packaging an application that depended on nostrum, I came across a runtime error that claimed the built-in Erlang httpd_util module was missing.  Adding :inets as an extra_application fixes the error, because distillery will bundle the httpd_util module while making a release.
=> Add dependency to :inets

lib/nostrum/struct/guild/member.ex, test/nostrum/struct/guild/member_test.exs
This is the stacktrace I was getting from calling `guild_channel_permissions`:
```
[
{Enum, :reduce, 2, [file: 'lib/enum.ex', line: 1869]},
{Nostrum.Struct.Guild.Member, :guild_channel_permissions, 3,
[file: 'lib/nostrum/struct/guild/member.ex', line: 164]},
{Bowser, :_check_set_perms, 1, [file: 'lib/bowser.ex', line: 46]},
{Bowser, :set_command, 2, [file: 'lib/bowser.ex', line: 68]},
{Bowser, :handle_event, 1, [file: 'lib/bowser.ex', line: 161]},
{Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]},
{:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}
]
%Enum.EmptyError{message: "empty error"}
```
I'm not entirely sure that `{0, 0}` is a good starting value?  At least the stacktrace is gone now and the correct permissions seem to be returned by the …
=> Avoid empty map error during permission fetch

lib/nostrum/api.ex, lib/nostrum/struct/user.ex
Added a default value for argument `locator` so that function's argument signature would match the non-banged counterpart.
=> Adjustment for Nostrum.Api.get_channel_messages!/3

.travis.yml, docs/static/Intro.md, lib/nostrum/api.ex, lib/nostrum/shard/dispatch.ex, lib/nostrum/struct/channel.ex, lib/nostrum/struct/embed.ex, lib/nostrum/struct/embed/author.ex, lib/nostrum/struct/embed/field.ex, lib/nostrum/struct/embed/footer.ex, lib/nostrum/struct/embed/image.ex, lib/nostrum/struct/embed/provider.ex, lib/nostrum/struct/embed/thumbnail.ex, lib/nostrum/struct/embed/video.ex, lib/nostrum/struct/emoji.ex, lib/nostrum/struct/guild.ex, lib/nostrum/struct/invite.ex, lib/nostrum/struct/message.ex, lib/nostrum/struct/user.ex, lib/nostrum/util.ex, mix.exs
Fix failing Travis master build
* Enum.map/2 |> Enum.into/2 --> Enum.into/3
* Added some Poison.Encoder aliases
* Ordering of aliases
* Bump Elixir version to 1.7.4
=> Fix Credo and Format errors, bump Elixir 1.7.4

lib/nostrum/shard/dispatch.ex, lib/nostrum/struct/guild/member.ex, lib/nostrum/struct/message.ex, lib/nostrum/util.ex
Updated Nostrum.Struct.Message for 1:1 field consistency with Message object sent by Discord.
Annotated the possibility for Nostrum.Struct.Guild.Member struct's field `user` being `nil`.
Message Update event will now provide a Nostrum.Struct.Message struct instead of a map, as event spec suggests.
Fixed warnings for having unused variables in Nostrum.Util.cast/2.
=> Added missing field for Nostrum.Struct.Message

lib/nostrum/struct/snowflake.ex, lib/nostrum/util.ex
With Elixir 1.8.0, calling functions from `DateTime` module with [deprecated time units](https://github.com/elixir-lang/elixir/blob/v1.8/CHANGELOG.md#4-hard-deprecations) will produce a warning on each function call.
```
warning: deprecated time unit: :milliseconds. A time unit should be :second, :millisecond, 
:microsecond, :nanosecond, or a positive integer
(elixir) lib/calendar/iso.ex:717: Calendar.ISO.precision_for_unit/1
(elixir) lib/calendar/iso.ex:708: Calendar.ISO.from_unix/2
(elixir) lib/calendar/datetime.ex:118: DateTime.from_unix/3
(elixir) lib/calendar/datetime.ex:166: DateTime.from_unix!/3
```
=> Replaced deprecated time units (1.8.0)

docs/static/API.md, docs/static/State.md, mix.exs
There's another broken link but I'm not sure what that's supposed to be: 
```elixir
warning: documentation references Nostrum.Struct.Emoji.format_custom_emoji/2 but it doesn't exist or it's listed as @doc false (parsing state docs)
```
=> Documentation: Display "Nostrum" as package name in sidebar, reference proper `Ratelimiter` callback

lib/nostrum/util.ex
Changes:
- Deleted `Util.producers/0`. From what I read on the discord, this is unused. If I misunderstood, give me a heads up.
- Fixed typespecs for `Util.gateway/0` and `Util.fullsweep_after/0`. These are purely static analysis fixes for dialyzer.
=> Dializer Fixes for `Nostrum.Util`

lib/nostrum/api.ex, lib/nostrum/constants.ex, lib/nostrum/struct/guild/audit_log.ex, lib/nostrum/struct/guild/audit_log_entry.ex
This PR adds support for retrieving audit logs. Right now it's more or less just parsing the response from the API. However, the API is a mess. A slight mess. A big mess. Pick your poison.
Since I'm not sure if we should structure this nicer (e.g. should we parse each audit log event type into its own struct? what about new audit log events here). Would be happy for some feedback.
=> Request for feedback: add initial audit log retrieval support

.travis.yml
Enables more credo checks to improve code uniformity. ~~Also prevents me from incorrectly ordering aliases.~~
=> Enabled credo `--strict` flag for travis

examples/cache.ex
As seen in https://github.com/jchristgit/bolt/commit/5f5586eaf3a64c1858c0023f4f73aed1842c1c57, when creating multiple consumer processes, the supervisor needs to have a unique ID (any term) to identify them.
=> Give unique IDs to per-scheduler consumers.

lib/nostrum/api.ex
- bad arity references
- inconsistent banged methods
- documented get_application_info/1
- kwl instead of map for edit_channel_permissions/2
- embed instead of list of embed (in accordance to discord's doc)
=> Documentation corrections

lib/nostrum/api.ex
Tested API methods:
- `modify_channel/2`
- `modify_channel/3`
- `create_channel_invite/2`
- `create_channel_invite/3`
- `modify_guild_emoji/2`
- `modify_guild_emoji/3`
- `modify_guild/2`
- `modify_guild/3`
- `add_guild_member_role/3`
- `add_guild_member_role/4`
- `remove_guild_member_role/3`
- `remove_guild_member_role/4`
- `remove_guild_member/3`
- `create_guild_ban/4`
- `create_guild_ban/3`
- `remove_guild_ban/3`
- `remove_guild_ban/2`
- `create_guild_role/2`
- `create_guild_role/3`
- `delete_guild_role/2`
- `delete_guild_role/3` (discord seems to ignore the reason here)
=> Support specifying audit log reasons in API-facing functions.

lib/nostrum/api.ex
Is there some way we could shorten this?
I have chosen \`\`\`elixir for syntax highlighting as I have found ​\`\`\`Elixir would not highlight the code - in ​contrast to #50, or is that there a typo?
=> Fix incorrect example for `modify_guild`.

lib/nostrum/api.ex
`Api.create_message` treats the options parameter as the message content if it is a string. This is represented in the typespec for `Api.create_message`. `Api.create_message!` simply passes the options parameter to `Api.create_message`, so it should have the same typespec for this parameter.
=> Fix Api.create_message! typespec

lib/nostrum/api.ex, lib/nostrum/constants.ex, lib/nostrum/consumer.ex, lib/nostrum/shard/dispatch.ex
Adds the new `MESSAGE_REACTION_REMOVE_EMOJI` event as well as a new API method `delete_reaction/3`.
hex release when?
=> Add MESSAGE_REACTION_REMOVE_EMOJI event and endpoint

lib/nostrum/api.ex
Default headers [`[{"content-type", "application/json"}]`](https://github.com/Kraigie/nostrum/blob/master/lib/nostrum/api.ex#L2833) added by `Nostrum.Api.request/4` causes `Nostrum.Api.leave_guild/1` to fail with `400: Bad Request` response.
=> Leaving guild fails with 400: Bad Request (#164)

.travis.yml
This PR adds the latest elixir version to CI as a safety check for nostrum's unit tests.
=> Add Elixir 1.10 to Travis CI

lib/nostrum/shard/event.ex
As of Elixir 1.10, any values other than strings, lists or maps passed to Logger results in a deprecation warning.
Example: warning: passing :PRESENCE_UPDATE to Logger is deprecated, expected a binary or an iolist
=> Fixes Logger deprecation warning.

examples/event_consumer.ex, lib/nostrum/api.ex, lib/nostrum/shard/dispatch.ex, lib/nostrum/struct/event/invite_create.ex, lib/nostrum/struct/event/invite_delete.ex, lib/nostrum/struct/event/message_delete.ex, lib/nostrum/struct/event/message_delete_bulk.ex, lib/nostrum/struct/invite.ex, test/nostrum/struct/invite_test.exs
+ Updated `Invite` struct to correctly reflect [Discord API's Invite object](https://discord.com/developers/docs/resources/invite)
+ Added event structs for previously unhandled events `INVITE_CREATE` and `INVITE_DELETE`
Praised be glorious :craig_cat:! May thou grant our daily head pats to our beloved people of Nostrum Empire! \o/
=> Updated `Invite` struct, added `INVITE_CREATE` and `INVITE_DELETE` events 

docs/static/Gateway Intents.md, docs/static/Intro.md, lib/nostrum/shard/intents.ex, lib/nostrum/shard/payload.ex, mix.exs, test/nostrum/shard/intents_test.exs
Adds support for gateway intents through a `gateway_intents` configuration option.
By default all intents are enabled, but passing the configuration option disables everything and only enables those passed.
There is an additional documentation page summarising how to specify gateway intents in the configuration.
=> Add gateway intents

lib/nostrum/api.ex
Adds `:allowed_mentions` as an option to `create_message`.
~~Shouldn't be merged until Discord API V8 is used by default.~~ Idk why that didn't work during development
=> Add support for allowed mentions

.github/workflows/test_and_lint.yml
This adds pull requests back into our integration. This was left out when we migrated from travis to github actions.
=> ci: add pull requests to workflow

lib/nostrum/api.ex
Updated `Nostrum.Api.update_status` to reflect `@type status :: :dnd | :idle | :online | :invisible`
=> fix: update_status now handles status as :atom

lib/nostrum/cache/guild_cache.ex
Title says it all.  The code references the `GuildSupervisor` without its full prefix (as if it was aliased) instead of the full path `Nostrum.Cache.GuildCache.all`.
This compiles because nothing at compile time knows that `GuildSupervisor` won't be a registered name.  At run time, however, the `GuildSupervisor` is named with its full path, so `Supervisor.which_children/1` can't find the process and exits with the expected `:noproc` status.
This fix adds an alias.
=> Nostrum.Cache.GuildCache.all/0 fails with EXIT :noproc

.github/workflows/test_and_lint.yml
> Elixir has a non-scary syntax and combines the good features of Ruby and Erlang. It's not Erlang and it's not Ruby and it has ideas of its own.
— Joe Armstrong
This PR drops Elixir 1.9 support.
It also caches the build directory for each matrix job (OTP version + Elixir version). This should hopefully decrease the CI time slightly. 💨
=> Improve CI speed

lib/nostrum/struct/guild/member.ex, test/nostrum/struct/guild/member_test.exs
Spotted by a test in `nosedrum`:
** (BadMapError) expected a map, got: [%Nostrum.Struct.Guild.Role{color: nil, hoist: nil, id: 125910, managed: nil, mentionable: nil, name: nil, permissions: 4, position: nil}]
code: assert {:noperm, _reason} = predicate.(message)
stacktrace:
(elixir 1.11.2) lib/map.ex:469: Map.get([%Nostrum.Struct.Guild.Role{color: nil, hoist: nil, id: 125910, managed: nil, mentionable: nil, name: nil, permissions: 4, position: nil}], 555, nil)
(elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
(nostrum 0.4.5) lib/nostrum/struct/guild/member.ex:121: Nostrum.Struct.Guild.Member.guild_permissions/2
(nosedrum 0.2.0) lib/nosedrum/predicates.ex:121: anonymous fn/2 in Nosedrum.Predicates.has_permission/1
test/nosedrum/predicates_test.exs:107: (test)
Tests are also …
=> Fix `guild_permissions` type failure.

lib/nostrum/consumer.ex
This has been blobbering up CI warnings for a while.
=> Kill unused alias.

lib/nostrum/consumer.ex
When calling `Nostrum.Consumer.start_link/2` from your own consumer, some option combinations will make it fail to start.
Currently, you can either pass the `name` option for the ConsumerSupervisor
```elixir
def start_link(mod, [name: name] = options) do
ConsumerSupervisor.start_link(
__MODULE__,
[mod, Keyword.drop(options, [:name])],
name: name
)
end
```
Or pass in the rest of the [options](https://kraigie.github.io/nostrum/Nostrum.Consumer.html#t:option/0) for the event handler module
```elixir
def start_link(mod, options),
do:
ConsumerSupervisor.start_link(
__MODULE__,
[mod, options]
)
```
If `name` and some of the other options get passed together to the `start_link` function, it will fail the first pattern match and put all given options as the event handler module options, making …
=> Fix Nostrum.Consumer options

lib/nostrum/struct/message.ex, lib/nostrum/struct/message/reference.ex
Adding support for `message_reference` and `referenced_message` for message objects: https://discord.com/developers/docs/resources/channel#message-object
Per contributing guidelines I ran `mix credo --strict`.  I got some warnings about TODOs, but they are unrelated to my changes.
=> Add support for reading message references

lib/nostrum/api.ex, lib/nostrum/struct/channel.ex, lib/nostrum/struct/emoji.ex, lib/nostrum/struct/event/message_delete.ex, lib/nostrum/struct/event/message_delete_bulk.ex, lib/nostrum/struct/guild.ex, lib/nostrum/struct/guild/member.ex, lib/nostrum/struct/message.ex
I implemented the new fields `rules_channel_id` and `public_updates_channel_id` that Discord recently added for public (discoverable) guilds.
Works properly in my testing. Per the contributing guidelines, I ran `mix credo --strict`, but the warnings that popped up didn't seem to be related to my changes.
=> Add new public guild fields

lib/nostrum/api.ex
Only two remainders found. Fixed here.
Closes #49.
=> Use `options` type instead of `keyword | map`.

lib/nostrum/struct/embed.ex, test/example_embed.ex
Basic implementation. If this approach is acceptable I'll add documentation about the usage, before merging.
=> Turn embed into a behaviour

lib/nostrum/voice/audio.ex
With `ffmpeg` now running with `-re` option, using voice with `youtube-dl` needs slightly more leeway on the watchdog timer.
=> Make a couple voice fixes

examples/cache.ex
Module name was at one point changed without also updating references to it.
=> Quick cache example fix

mix.exs
This is not required by users of the library, but can be useful when we are
debugging the library ourselves.
=> Make `recon` dependency optional.

lib/nostrum/shard/dispatch.ex
The tuple sent here only had a single element, whilst being typespecced as
directly passing through the guild struct.
Fixes #220.
=> Pull `:GUILD_{AVAILABLE,CREATE}` payload out of tuple.

lib/nostrum/api.ex
When receiving a successful response from webhook execution, it would be unnecessarily passed for decoding and raise
```elixir
** (FunctionClauseError) no function clause matching in Nostrum.Api.handle_request_with_decode/1
The following arguments were given to Nostrum.Api.handle_request_with_decode/1:
{:ok}
Attempted function clauses (showing 2 out of 2):
defp handle_request_with_decode(-{:ok, body}-)
defp handle_request_with_decode(-{:error, _} = error-)
(nostrum 0.4.6) lib/nostrum/api.ex:3255: Nostrum.Api.handle_request_with_decode/1
```
=> Remove response decode from `Api.execute_webhook/4`

lib/nostrum/api.ex, lib/nostrum/struct/guild/ban.ex
```elixir
iex(2)> Nostrum.Api.get_guild_ban(x, y)
{:ok,
%Nostrum.Struct.Guild.Ban{
reason: "spamming",
user: %Nostrum.Struct.User{
avatar: "xxxx",
bot: nil,
discriminator: "0000",
email: nil,
id: zzzz,
mfa_enabled: nil,
public_flags: %Nostrum.Struct.User.Flags{
bug_hunter_level_1: false,
bug_hunter_level_2: false,
early_supporter: false,
hypesquad_balance: false,
hypesquad_bravery: true,
hypesquad_brilliance: false,
hypesquad_events: false,
partner: false,
staff: false,
system: false,
team_user: false,
verified_bot: false,
verified_developer: false
},
username: "gggg",
verified: nil
}
}}
```
=> Continuation from #110: Add get_guild_ban and fix typo, cast into struct.

lib/nostrum/api/ratelimiter.ex
It looks like discord is now sending lowercased rate limiting headers (e.g. "x-ratelimit-global" instead of "X-RateLimit-Global"), which breaks the current code.
With this PR, I am making sure this doesn't happen again by forcing all processed headers to be lowercased no matter what. I am also adding a `headers_to_keep` MapSet to improve filtering speed. Indeed, we now get all our headers in one pass compared to 5 with the previous `List.keyfind` solution.
Sampled headers within the `HTTPoison.Response` in `Nostrum.Api.Ratelimiter.handle_headers`:
```
{"Date", "Thu, 27 May 2021 16:52:09 GMT"},
{"Content-Type", "text/html; charset=utf-8"},
{"Content-Length", "0"},
...
{"x-ratelimit-bucket", "c7f060a5d9790cb6f53000110a7b7edf"},
{"x-ratelimit-limit", "10"},
{"x-ratelimit-remaining", "5"}, …
```
=> Fix rate limiting broken by casing of x-ratelimit-xxx headers

lib/nostrum/shard/session.ex
The `UnprocessedStreams` parameter was removed in gun 2.0.
[gun_down in 1.3](https://ninenines.eu/docs/en/gun/1.3/manual/gun_down/)
[gun_down in 2.0](https://ninenines.eu/docs/en/gun/2.0/manual/gun_down/)
=> Fix `gun_down` crash caused by gun 2.0 migration

lib/nostrum/api/ratelimiter.ex
I think we all want stability in a library like Nostrum so I understand why a sanity wait was added in the first place. 
However, 500ms seems like a very long time to wait in addition to an accurate retry-after. Furthermore, the time it took for the original request to come back with the rate limiting header in addition to the time it will take for the retried request to reach discord servers (let's say 50ms for each at best) should be more than enough to guarantee we are well over the retry-after limitation.
If you are not comfortable removing it entirely, then let us please consider lowering it to something like 100ms.
=> Remove overly cautious "sanity wait" for rate limiting

lib/nostrum/struct/message.ex
Takes the message and produces a URL that, when clicked from the user client, will   jump them to that message, assuming they have access to the message and the message is valid.
Note: this is the output of Credo, however none of these were added by my commit. I can add the newline if desired.
>   Software Design                                                                                                                                           
┃ 
┃ [D] → Found a TODO tag in a comment: # TODO: Jump down the rabbit hole
┃       lib/nostrum/struct/embed.ex:518 #(Nostrum.Struct.Embed.from)
┃ [D] → Found a TODO tag in a comment: # TODO: Once gun 2.0 is released, the block below can be simplified to:
┃       lib/nostrum/shard/session.ex:86 #(Nostrum.Shard.Session.await_ws_upgrade)
┃ [D] → …
=> Create `to_url` function for Message

lib/nostrum/struct/message.ex
Resolves a credo nag that was preventing CI from passing.﻿
=> Remove whitespace from Nostrum.Struct.Message

lib/nostrum/cache/guild/guild_server.ex, lib/nostrum/consumer.ex, lib/nostrum/shard/dispatch.ex, lib/nostrum/shard/event.ex, lib/nostrum/struct/application_command_interaction_data.ex, lib/nostrum/struct/application_command_interaction_data_option.ex, lib/nostrum/struct/application_command_interaction_data_resolved.ex, lib/nostrum/struct/event/channel_pins_update.ex, lib/nostrum/struct/event/guild_ban_add.ex, lib/nostrum/struct/event/guild_ban_remove.ex, lib/nostrum/struct/event/guild_integrations_update.ex, lib/nostrum/struct/event/message_reaction_add.ex, lib/nostrum/struct/event/message_reaction_remove.ex, lib/nostrum/struct/event/message_reaction_remove_all.ex, lib/nostrum/struct/event/message_reaction_remove_emoji.ex, lib/nostrum/struct/event/partial_application.ex, lib/nostrum/struct/event/ready.ex, lib/nostrum/struct/event/typing_start.ex, lib/nostrum/struct/event/voice_server_update.ex, lib/nostrum/struct/event/voice_state.ex, lib/nostrum/struct/interaction.ex, lib/nostrum/util.ex, lib/nostrum/voice/session.ex, test/nostrum/struct/interaction_test.exs
This is only adjusted in the session and voice session dispatcher. That said,
it should be compatible with the current code: atoms are transformed in most
`to_struct` methods via `maybe_to_atom` anyways. In order to fix an atom leak,
the following changes are introduced additionally:
- Adding new keys from the API to interaction structs.
- Adding the `ApplicationCommandInteractionDataResolved` struct.
This may or may not break some things. I will test it with
[bolt](https://github.com/jchristgit/bolt) to look out for any problems, but if
I inferred everything correctly, it would work just fine with existing code.
Note that the new way of converting incoming data to structs also allows us to
slowly phase out `maybe_to_atom`, with the drawback that we need to specify
parsed keys manually. …
=> Do not cast all incoming keys to atoms.

lib/nostrum/voice/audio.ex
Porcelain process spawning functions can return an error tuple even though it's not specified in the type specs. Until [this PR](https://github.com/alco/porcelain/pull/54) is merged and Porcelain has another release, these added attributes will allow dialyzer to ignore the false positives.
=> Ignore dialyzer warnings for functions that use Porcelain.

README.md, config/config.exs, docs/static/Gateway Intents.md, docs/static/Intro.md, lib/nostrum/util.ex
Attempt to decomplicate a bit. Nostrum is built on Erlang, and Erlang is
smart, so we do not need to document this configuration value, as it is
not needed. Save users some time.
=> Do not document `num_shards` setting.

lib/nostrum/struct/guild/integration.ex
This was previously only a stub, and caused dialyzer to throw up.
=> Define `Nostrum.Struct.Guild.Integration`.

lib/nostrum/struct/event/message_delete.ex
`:guild_id` is not set when a direct message is deleted. This change ensures that we don't crash when that happens.
=> Fix `MessageDelete.to_struct` for direct messages

lib/nostrum/api.ex
Changes the spelling of `:user` and `:role` in the documentation to be pluralised correctly to match how it actually is in the code. Accidentally pinged everyone thanks to this, good thing it was in a testing guild 😅
Relevant lines
https://github.com/Kraigie/nostrum/blob/517894fd9d256210c3acdf5698b2dcc3be5b4990/lib/nostrum/api.ex#L3352-L3358
=> docs: correct spelling of allowed_mentions atoms

lib/nostrum/struct/application_command_interaction_data.ex
These fields will not be present on button interaction events, as such they have been changed to be optional fields
Tested this on my own bot to confirm.
=> Make `id` and `name` optional for interaction data

lib/nostrum/cache/guild_cache.ex
Regression from the ETS guild cache migration.
=> Return old guild on guild update.

lib/nostrum/struct/application_command_interaction_data_option.ex
The `to_struct/1` fn in `Nostrum.Struct.ApplicationCommandInteractionDataOption` was not passing the correct arguments to `Nostrum.Util.cast/2`
Leading to an `UndefinedFunction` error when a slash command's sub-command is called.
=> Fix ModuleUndefined error in InteractionOption

lib/nostrum/struct/interaction.ex
This makes most fields in an interaction possibly `nil` for when it's part of a message.
Should this honestly instead be replaced with a `PartialInteraction` struct?
fixes #320
=> make interaction fields optional

lib/nostrum/struct/application_command_interaction_data.ex
`InteractionData` was missing the `target_id`, `type`, and `values` fields for [InteractionData](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-data-structure). This PR adds them.
=> Add three missing fields to interaction data

mix.exs
Elixir version 1.9 has been untested in CI for a while now, per
https://github.com/Kraigie/nostrum/pull/193.
This does not adjust the version in any installation guides yet, as we
have not (and can not) published a release yet.
=> Bump version and Elixir version.

lib/nostrum/cache/guild_cache.ex, lib/nostrum/struct/application_command_interaction_data.ex, lib/nostrum/struct/guild.ex
This fixes a fatal bug where if a Guild is updated, a member or channel update will then cause a `BadMapError`.
=>  Fix `GUILD_UPDATE` making some fields `nil` 

lib/nostrum/struct/application_command_interaction_data.ex, lib/nostrum/struct/application_command_interaction_data_option.ex, test/nostrum/struct/interaction_test.exs
Discord sends other types than string here occasionally. That said, when
a snowflake arrives, we want to decode it from string to integer, which
makes looking it up in the `resolved` type easier. Document the new
types for the user.
Fixes #235.
=> Parse interaction types properly and document types.

.github/workflows/docs.yml, docs/static/Intro.md
- Change docs workflow to build with Elixir v1.12
- Change Intro.md to specify that Nostrum targets Elixir v1.10 and up
=> Fix docs workflow

lib/nostrum/application.ex, lib/nostrum/cache/cache_supervisor.ex, lib/nostrum/cache/guild_cache.ex, lib/nostrum/cache/guild_cache/ets.ex, lib/nostrum/cache/user_cache/ets.ex, mix.exs, test/nostrum/cache/guild_cache_test.exs
Similar to the pluggable user cache, this allows developers to choose
their own caching mechanism for structures received from Discord.
However, the approach taken here also differs slightly from the user
cache implementation to make improvements aimed at completely decoupling
the chosen cache implementation from nostrum itself. The following base
functionality is provided:
- Cache behaviour and dispatching module `Nostrum.Cache.GuildCache` with
accompanying documentation.
- Default cache behaviour implementation `Nostrum.Cache.GuildCache.ETS`,
which is the current ETS-based guild cache implementation.
Two architectural changes are made here in contrast to the user cache:
1. Guild cache implementations are supervisors. This allows any
implementations to completely manage what they do on …
=> Implement pluggable guild caching.

lib/nostrum/shard/dispatch.ex
Most people will probably need to know in which guild a member was added so we should add the guild_id to the payload (that's what `member_remove` and `member_update` already do).
Can you please suggest a way to make this change backwards compatible?
=> Add guild_id to a guild's member_add event dispatch

lib/nostrum/shard/session.ex
Like it says on the tin.
This was the only part still using v6, everything should already be v8 ready from when we updated the api version to v8.
=> change gateway to v8

lib/nostrum/struct/event/voice_state.ex
`member` is apparently an atom and not a string key in voice state payloads
=> Fix member cast in VoiceState.to_struct

lib/nostrum/api.ex, lib/nostrum/constants.ex
This adds `edit_webhook_message`, `edit_interaction_response` and `delete_interaction_response` to `Nostrum.Api`.
=> Add missing Api endpoints

lib/nostrum/struct/guild/role.ex, test/nostrum/struct/guild/role_test.exs
Noticed when trying to get guild permissions for a user that permissions where being given as a string for some reason, resulting in an arithmetic error with the function using `:erlang.bor`, and sure enough listing roles and their permissions gives a list of strings:
```elixir
iex(3)> Nostrum.Cache.GuildCache.get!(441529557691006977).roles |> Enum.map(fn {_, role} -> role.permissions end)
["1071698533952", "6546644544", "8559918328"]
```
This adds an extra step in `Role.to_struct` that parses permissions if its a string, and corresponding test to make sure it works properly.
=> fix: Parse role permissions if they're a string

lib/nostrum/cache/guild_cache/ets.ex
This fixes an issue where if a ready event is re-emitted for any reason a fatal error in the cache would occur due to disallowing duplicate Guild inserts.
Instead they are now treated as replace operations.
=> Duplicate guild creates should be a cache replace

lib/nostrum/api.ex
Apparently `edit_interaction_response` did not decode the response from discord before
=> Make edit_interaction_response decode

lib/nostrum/application.ex, lib/nostrum/cache/cache_supervisor.ex, lib/nostrum/cache/presence_cache.ex, lib/nostrum/cache/presence_cache/ets.ex, mix.exs, test/nostrum/cache/presence_cache_test.exs
Based off `pluggable-guild-cache` to prevent merge conflicts.
This uses the same approach as the pluggable guild cache, in that we
have a base behaviour and dispatcher for the presence cache, and a
ETS-based implementation chosen by default which uses the current
implementation. A small test is added to ensure correct cache function.
=>      Implement pluggable presence caching.     

lib/nostrum/cache/guild_cache.ex, lib/nostrum/cache/guild_cache/ets.ex, mix.exs, test/nostrum/cache/guild_cache_test.exs
Guild caches provide banged methods such as `get!/1`, `select!/2` and
friends, which were implemented directly in the backing guild cache. It
makes more sense to define these once in the dispatcher to prevent
having to duplicate logic across cache backends. This is already being
performed in the pluggable user cache.
=> Simplify bangify methods in guild cache.

lib/nostrum/struct/message.ex, lib/nostrum/struct/message/component.ex
Define component type and re-enable parsing of message components.
Fixes #323.
=> Enable component parsing.

lib/nostrum/voice/audio.ex
Occasionally the watchdog timer responsible for detecting end of input is fired after `pause/1` is called, which causes the sound to abruptly end after `resume/1`. 
Fixes #368
=> Fix bug with rogue watchdog timer.

docs/static/Intro.md, docs/static/Voice.md, lib/nostrum/voice/audio.ex
This config option will allow for proper playback of extremely short audio files.
=> Add option to configure number of audio frames to send for each burst before sleeping.

lib/nostrum/voice/session.ex
This was done to `Nostrum.Shard.Session` already when migrating from `:gun` `1.3` to `2.0`.
=> Practice proper :gun2.0 safety

lib/nostrum/cache/presence_cache/noop.ex
Useful for bots that do not care about presences and want to save on
memory.
=> Add a no-op presence cache.

config/.credo.exs, lib/nostrum/struct/application_command_interaction_data.ex, lib/nostrum/struct/application_command_interaction_data_option.ex, lib/nostrum/struct/component/option.ex, lib/nostrum/struct/event/guild_ban_add.ex, lib/nostrum/struct/event/guild_ban_remove.ex, lib/nostrum/struct/event/guild_integrations_update.ex, lib/nostrum/struct/event/message_delete.ex, lib/nostrum/struct/event/message_reaction_add.ex, lib/nostrum/struct/event/message_reaction_remove.ex, lib/nostrum/struct/event/message_reaction_remove_all.ex, lib/nostrum/struct/event/message_reaction_remove_emoji.ex, lib/nostrum/struct/event/partial_application.ex, lib/nostrum/struct/event/ready.ex, lib/nostrum/struct/event/typing_start.ex, lib/nostrum/struct/event/voice_state.ex, lib/nostrum/struct/guild/integration.ex, lib/nostrum/struct/interaction.ex, lib/nostrum/struct/message/component.ex
Now all the `to_struct/1` functions should follow the same pattern.
And from `VoiceState` I removed the `?` from field names to maintain consistency across the rest of the library and the 1:1 field mapping with the API.
While writing this PR, I noticed that I missed a couple places when replacing ISO8601 strings with the `DateTime` struct as well as a couple Unix Timestamp fields. I'll open a PR for those after this gets merged.
=> Improve consistency of `to_struct` fns and remove `?` from field names

lib/nostrum/api.ex
Adds the option to include files when creating interaction responses. As an added bonus, the file's body can be an iolist and work just fine.
=> Allow for uploading files in interaction responses

lib/nostrum/struct/guild/member.ex
Added the `premium_since` field to the Guild Member struct for use in determining if a user is actively boosting a guild.
Reference Documentation:
[Guild Member Object (Discord API)](https://discord.com/developers/docs/resources/guild#guild-member-object)
Sample Guild Member:
```
%Nostrum.Struct.Guild.Member{
communication_disabled_until: nil,
deaf: false,
joined_at: "2020-12-29T17:18:07.964000+00:00",
mute: false,
nick: nil,
premium_since: ~U[2022-02-08 23:57:37.225000Z],
roles: [111111111111111111],
user: %Nostrum.Struct.User{
avatar: "f2464bd69e949680135b0eeb99c7a2fa",
bot: nil,
discriminator: "0001",
email: nil,
id: 222222222222222222,
mfa_enabled: nil,
public_flags: %Nostrum.Struct.User.Flags{
bug_hunter_level_1: false,
bug_hunter_level_2: false,
early_supporter: false, …
```
=> Added `premium_since` field to Guild Member

lib/nostrum/shard/dispatch.ex
Fixes the issue where the `READY` event doesn't use the struct created for it.
=> `READY` event now uses ready struct

lib/nostrum/voice/audio.ex
`player_pid` isn't current on the first iteration of `player_loop` so the `on_stall` check fails and causes the player to stall if the audio source times out or fails before producing any audio.
=> Fix bug where voice player stalls on initial timeout

config/config.exs, lib/nostrum/error/voice_error.ex, lib/nostrum/struct/voice_state.ex, lib/nostrum/voice.ex, lib/nostrum/voice/audio.ex, lib/nostrum/voice/ports.ex, mix.exs, mix.lock
Removing Porcelain as a dependency, which has not had a new release in many years, and using native Erlang ports instead with fewer processes than Porcelain uses.
Also takes care of closing secondary processes piping into ffmpeg when ffmpeg is closed.
Various readability improvements.
Yes it works.
=> Use native ports instead of porcelain

lib/nostrum/shard/dispatch.ex, lib/nostrum/struct/voice_state.ex, lib/nostrum/voice.ex
Optionally persist playback when joining a different channel in a guild already playing audio in.
Automatically plays when if audio was playing at time of channel change. Audio is `resume/1`able if audio was `pause/1`d at the time of channel change.
Funcs for testing
```elixir
def join_voice, do: Voice.join_channel(@guild_id, @channel_id)
def join_voice_2, do: Voice.join_channel(@guild_id, @channel_id_2)
def join_voice_no, do: Voice.join_channel(@guild_id, @channel_id, false, false, false)
def join_voice_2_no, do: Voice.join_channel(@guild_id, @channel_id_2, false, false, false)
def play(url \\ "https://www.youtube.com/watch?v=o_hXGZ8NXAA", opts \\ []),
do: Voice.play(@guild_id, url, :ytdl, opts)
def pause(), do: Voice.pause(@guild_id)
def resume(), do: Voice.resume(@guild_id)
### …
```
=> Persistent playback through channel switches

lib/nostrum/struct/guild/audit_log.ex
`Nostrum.Struct.Guild.AuditLog` has an `:entries` key, while the API
returns an `:audit_log_entries`. However, when casting the response, the
`:audit_log_entries` field was casted. Since there was no `:entries`
field in the resulting map, when calling `struct/2`, `:entries` was
always `nil`.
=> Fix audit log entries not being saved

lib/nostrum/api.ex, lib/nostrum/constants.ex, lib/nostrum/consumer.ex, lib/nostrum/permission.ex, lib/nostrum/shard/dispatch.ex, lib/nostrum/shard/session.ex, lib/nostrum/struct/channel.ex, lib/nostrum/struct/event/thread_list_sync.ex, lib/nostrum/struct/event/thread_members_update.ex, lib/nostrum/struct/guild.ex, lib/nostrum/struct/message.ex, lib/nostrum/struct/thread_member.ex
Add support for Threads
Why bump to API v9 in this PR and not skip directly to v10? Because these should be able to be done without it being a breaking change, allowing for one last hex release before v10 and `0.6.0`
=> Threads support

lib/nostrum/consumer.ex, lib/nostrum/shard/dispatch.ex, lib/nostrum/struct/event/guild_integration_delete.ex, lib/nostrum/struct/guild/integration.ex, lib/nostrum/struct/guild/integration/account.ex, lib/nostrum/struct/guild/integration/application.ex
Adds in three events we haven't implemented, `INTEGRATION_CREATE`, `INTEGRATION_UPDATE`, and `INTEGRATION_DELETE`
=> Define `integration_*` events

lib/nostrum/voice/opus.ex
Three main things
1. **Fix bug with generating ogg pages with incorrect page_segments value.** - _page_segments is the byte length of the segment_table, and when segments exceed 254 bytes they take up multiple bytes in the segment table. This was leading to some encoding errors when some opus packets were 255 bytes in length or greater._
2. **Properly skip over rtp header extension.** - _the ext_length is actually the number of 32 bit words of the extension, not the number of extension elements to iterate through. Thanks to @imayhaveborkedit for pointing me to the first paragraph of the rfc 🤡_ 
3. **Place binary pattern matches in function headers versus body.** - _good practice_
=> Ogg encoding and rtp ext fixes

lib/nostrum/struct/guild/integration.ex, lib/nostrum/struct/guild/integration/application.ex
Improperly wrote the calls to `Util.cast/2`, this fixes that.
=> fix improper call to `Integration` cast bug

lib/nostrum/struct/interaction.ex
Adds two missing fields to the `Interaction` struct.
=> add `locale` and `guild_locale`

lib/nostrum/struct/event/speaking_update.ex, lib/nostrum/struct/voice_state.ex, lib/nostrum/voice.ex, lib/nostrum/voice/audio.ex, lib/nostrum/voice/opus.ex, lib/nostrum/voice/payload.ex, lib/nostrum/voice/ports.ex
Lots of readability and performance improvements and extra info in docs
A number of things gleaned from niche use cases and edge cases encountered while heavily testing an audio bot:
- a fix to close ports safely
- new feature/fields for last played URL
- fixes for `:raw` type playing
- fix for rogue watchdog canceling subsequent audio if played immediately after stopping previous audio
=> Improve pad_opus, define constants, fix various player bugs, code cleanup, current url feature

lib/nostrum/application.ex, lib/nostrum/token.ex, test/nostrum/token_test.exs
Generating a Discord Bot Token will sometimes return a longer token format than what the `check_token/1` function is checking for.
This will currently throw the following error:
```elixir
** (Mix) Could not start application nostrum: exited in: Nostrum.Application.start(:normal, [])
** (EXIT) an exception was raised:
** (RuntimeError) Invalid token format, copy it again from the `Bot` tab of your Application
(nostrum 0.5.1) lib/nostrum/application.ex:40: Nostrum.Application.check_token/1
(nostrum 0.5.1) lib/nostrum/application.ex:10: Nostrum.Application.start/2
(kernel 8.2) application_master.erl:293: :application_master.start_it_old/4
```
I wasn't able to reliably find a triggering setting but this is an example token (Already resetted, so it's unusable) …
=> Fix `check_token/1` for variable length tokens

lib/nostrum/struct/message.ex
Previously this function didn't work if any of the snowflakes were integers, now it will work as intended.
Yes I know `IO.iodata_to_binary()` is probably overkill here.
=> Fix a bug related to `Message.to_url`

lib/nostrum/api.ex
A few fields in the possible arguments here should be marked as optional, and file content for upload can successfully be `iodata`, not just a `binary`.
=> fix dialyzer issues with webhooks

lib/nostrum/token.ex
i was running into problems starting the bot and noticed my userid in the discord token was not a multiple of 4 and also not padded. using elixir modules for base64 seems to solve this by passing the padding: false option. not sure if there's a reason to stick with erlang modules though.
=> support non padded base64 userid in the discord bot tokens

docs/static/API.md
While using Nostrum with Rest Only approach, an error occurred in runtime of build (released with mix release):
```
[info] Application example exited: exited in: Example.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) The module Nostrum.Api.Ratelimiter was given as a child to a supervisor but it does not exist.
            (elixir 1.12.2) lib/supervisor.ex:631: Supervisor.init_child/1
```
The cause of it related to all `runtime: false` deps are not included into build, while building with `mix release`. 
I decided to add this info to docs as a time saver for devs, who will meet this non-obvious problem only in production.
=> Add information to Api Rest only section

lib/nostrum/struct/application_command_interaction_data.ex
Brought up in issue 434 https://github.com/Kraigie/nostrum/issues/434 
Checked code and seems to fix the dialyzer warning.
=> incorrect typespec for options in ApplicationCommandInteractionData

lib/nostrum/voice/audio.ex
Fixes a bug where certain videos wouldn't play.
Example video that Nostrum won't play: https://www.youtube.com/watch?v=NjgFKUooYHY
In more detail, the bug occurs when yt-dlp/youtube-dl prints a warning to stderr. Since stderr is redirected to stdout, the warning text will be present at the top or near the start of the output which is sent to ffmpeg, which obviously causes issues when ffmpeg tries to transcode the audio.
The following warning is printed out by yt-dlp (dunno how it is for youtube-dl) when trying to download the video above: `WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = Y4TUHHipURV8t0Kjw4 ; player = https://www.youtube.com/s/player/4c3f79c5/player_ias.vflset/en_US/base.js`
Adding "--no-warnings" to the command-line options …
=> Add "--no-warnings" to ytdl command-line options

lib/nostrum/voice/opus.ex
Discord sometimes sends us RTP packets without headers, which make nostrum crash with the following error:
```
20:52:08.330 [error] GenServer #PID<0.765.0> terminating
** (FunctionClauseError) no function clause matching in Nostrum.Voice.Opus.strip_rtp_ext/1
(nostrum 0.6.1) lib/nostrum/voice/opus.ex:34: Nostrum.Voice.Opus.strip_rtp_ext(<<252, 255, 254>>)
(nostrum 0.6.1) lib/nostrum/voice/session.ex:154: Nostrum.Voice.Session.handle_info/2
(stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
(stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
(stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
This patch fixes this problem. I believe discord.js processes RTP packets in the same way as this patch ([here](https://github.com/discordjs/discord.js/blob/d8e774138d5 …
=> Accept RTP packet without header

lib/nostrum/api.ex, lib/nostrum/struct/guild/role.ex, test/nostrum/struct/guild/role_test.exs
Tested this with a local copy and it seems to properly populate the `:icon` field into the struct from the API response.
=> Support role icons

lib/nostrum/api.ex, lib/nostrum/constants.ex, lib/nostrum/consumer.ex, lib/nostrum/shard/dispatch.ex, lib/nostrum/shard/intents.ex, lib/nostrum/shard/payload.ex, lib/nostrum/struct/auto_moderation_rule.ex, lib/nostrum/struct/auto_moderation_rule/action.ex, lib/nostrum/struct/auto_moderation_rule/action_metadata.ex, lib/nostrum/struct/auto_moderation_rule/trigger_metadata.ex, lib/nostrum/struct/event/auto_moderation_rule_execute.ex, test/nostrum/shard/intents_test.exs
Just like it says on the tin. Some further testing would be appreciated as I'm unable to test this feature fully at present, hasn't rolled out to my test guild yet.
=> Resolve deprecation of `$` prefixing properties in identify payload, and add support for auto-mod

lib/nostrum/api.ex, lib/nostrum/struct/channel.ex
Implements forum channels and adds the new channel fields to the channel struct.
Note: There is an inconsistency between how creating a thread with multi-part form data actually works and how it is documented, I've asked for clarification on the matter. Can confirm this works at the moment but may be unintentional.
=> implement forum channels

lib/nostrum/api.ex, lib/nostrum/struct/guild/role.ex, test/nostrum/struct/guild/role_test.exs
Apparently the image icon (from #441) is separate from the emoji icon, so we need this too.
=> Support emoji role icons

lib/nostrum/shard/dispatch.ex, lib/nostrum/shard/supervisor.ex, lib/nostrum/struct/voice_state.ex, lib/nostrum/voice.ex, lib/nostrum/voice/ports.ex, lib/nostrum/voice/session.ex, lib/nostrum/voice/supervisor.ex
I had noticed my bot hell looping trying to reconnect after getting a voice ws error 4006 so I'm leaving less to chance when sequencing events for reconnecting. Using cast in some places to reduce blocking processes. The get reactions api changes are unrelated because I forgot I had those unstaged changes in my branch.
=> Minor voice refactors and improve get reactions api call

lib/nostrum/cache/guild_cache/ets.ex, lib/nostrum/consumer.ex
Issue #452 outlines a problem where if the guild member intent is enabled but the guild intent is not, Nostrum will crash upon trying to look up the guild in the guild cache table. Instead of doing a hard match here, cross-check it in a `case` and if we do not have it cached, simply fan out the guild ID and the partial member object to the consumer.
Closes #452.
=> Prevent crashing guild cache without guilds intent

lib/nostrum/struct/component/button.ex
Replaces the functions `enable/1` and `disable/1` from `Nostrum.Struct.Component.Button` with the function `enable/2` and fixes a crash in `toggle/1`
=> Fix button status

lib/nostrum/shard/dispatch.ex, lib/nostrum/voice.ex, lib/nostrum/voice/session.ex
Fix bug where when session_pid was dead, joining a voice channel would make a gen server call to the dead session and would end up crashing a cache.
This situation shouldn't occur since the session processes are supervised and they should be alive for the duration that the bot is connected to a voice channel, but I've seen it occur a couple times and it ended up crashing the bot. I suspect it may be due to gun2.0 or due to other recent async voice reconnect changes, but this change covers that case now.
Simplify `on_channel_join_change` as voice events always come in in guaranteed order so calling the session gen server isn't necessary so we can further reduce number of gen server calls.
=> Fix crash when trying to connect when session pid isn't alive

lib/nostrum/cache/channel_cache/ets.ex, lib/nostrum/cache/member_cache/ets.ex, lib/nostrum/cache/presence_cache/ets.ex, lib/nostrum/cache/user_cache/ets.ex
This allow us to return arbitrary references later once (if) we support running nostrum as a library instead of an application.
=> Use more generic `table/0` instead of `tabname`

lib/nostrum/cache/guild_cache/ets.ex, test/nostrum/cache/guild_cache_test.exs
Needed when guilds intent is disabled.
=> Support member count operations for uncached guilds

lib/nostrum/api/ratelimiter.ex, lib/nostrum/error/api_error.ex, lib/nostrum/store/ratelimit_bucket.ex
First off, a retry_after time of exactly `0` is also a "you can go now": even if it represents some minimal value like 0.001, the network latency will eat that up anyways. Next up, if the ratelimiter asks us to retry and we do, handle the case where another process managed to race us and we need to sit it out again, with up to three retries.
Closes #493.
=> Prevent crash with retry_after

lib/nostrum/struct/interaction.ex
Like it says on the tin. New `:channel` field to replace `channel_id` which they say will eventually be deprecated and removed.
=> add new channel field to interactions

lib/nostrum/consumer.ex
A couple of additions to `Nostrum.Consumer`:
- Use `@impl` declarations where appropriate.
- Add a `@behaviour Nostrum.Consumer` declaration to `__using__`.
- Add a `__before_compile__` hook to inject a default `:noop` implementation of `handle_event`.
=> Add `@behaviour`, `@impl` and default `handle_event` to `Nostrum.Consumer`

lib/nostrum/application.ex, lib/nostrum/state_machine_translator.ex, mix.exs
Elixir will, by default, not output `:gen_statem` errors, which is ... suboptimal. We add a new logger translator to deal with these errors and report them.
=> Add state machine report translator

appup.ex, lib/nostrum/application.ex, lib/nostrum/shard/event.ex, lib/nostrum/shard/session.ex, lib/nostrum/struct/ws_state.ex
This fixes the previous implementation's problem of retrying connections indefinitely without any proper handling of errors. Ratelimiting will be added separately.
=> Convert shard sessions into state machines

lib/nostrum/util.ex
`Session.get_ws_state` now returns the tuple `{:connected, %WSState{}}`, it was causing KeyNotFound errors to be raised.
=> Fix Util.get_all_shard_latencies

lib/nostrum/shard/event.ex, lib/nostrum/shard/session.ex
fix reconnect requests from discord to make it so we resume properly and without an infinite loop.
Was unable to test fully, do not merge until someone has had a chance to.
=> Fix reconnect requests

lib/nostrum/util.ex
We probably shouldn't crash when the gateway accidentally leaks these keys
Closes #511
=> don't crash when discord leaks a struct

lib/nostrum/api/ratelimiter.ex
Discord has stopped allowing http2 connections for the time being, guessing its related to `CVE-2023-44487`
=> allow http1 connections in ratelimiter

.github/workflows/docs.yml, .github/workflows/test_and_lint.yml, appup.ex, benchmarks/qlc_bench.exs, lib/nostrum/cache/channel_cache.ex, lib/nostrum/cache/channel_cache/noop.ex, lib/nostrum/cache/guild_cache.ex, lib/nostrum/cache/guild_cache/noop.ex, lib/nostrum/cache/member_cache.ex, lib/nostrum/cache/member_cache/ets.ex, lib/nostrum/cache/member_cache/noop.ex, lib/nostrum/cache/presence_cache.ex, lib/nostrum/cache/presence_cache/noop.ex, lib/nostrum/cache/user_cache.ex, lib/nostrum/cache/user_cache/noop.ex, mix.exs
Since we use `:pg.monitor/2` within Nostrum and it was introduced in OTP 25.1, this bumps the Elixir version mentioned in our `mix.exs` to the earliest version of Elixir which officially supports OTP 25. Also updates CI to include the latest versions of OTP and Elixir while dropping unsupported versions.
=> bump minimum elixir version and test matrix

lib/nostrum/shard/session.ex
Instead of relying on the user to interpret the existing debug logs and badmatch error, send an explicit error message when no consumer could be found that we can use in the shard connection. See #524.
=> Add error message for lacking consumer startup

lib/nostrum/shard/dispatch.ex
Previously, we would only store created text and voice channels in the channels field of guilds in the `GuildCache`.
This was weird, because on application start, we would cache all channels regardless of type.
This removes that restriction to allow all channels to be cached and queried.
=> Store all channels in channel cache

lib/nostrum/api.ex
Run `combine_files()` for all message endpoints
This ensures that we are actually handling the cases that we claim to
support, passing both paths and uploading files from memory (by using a
map).
We previously had changed this behaviour which meant that path uploading
was working but users could not create files from memory, which is a
heavily used feature and was not intentionally removed.
=> Re-support uploading files from memory

lib/nostrum/struct/channel.ex
Adds the following admonition to explain why DM channels are not/cannot be cached:
=> Add admonition documenting lack of DM channel caching

.github/workflows/test_and_lint.yml
We can catch any potential snags with Nostrum on OTP 27 here.
I have disabled OTP 27 being used with Elixir v1.14 as that is not going to be a combination we see in production.
If we do have failures on this suite under the OTP release candidate we should investigate it but not make it a required criterion for merges.
=> Add OTP 27.0-rc3 to our test matrix

lib/nostrum/api.ex
This will be useless once / if we support multiple bots or library
usage, and at the moment it simply returns a value that the user sets
and can read on his or her own.
=> Remove Nostrum.Api.get_token

lib/nostrum/util.ex
This fixes a bug reported in the DAPI channel which caused the Shard state machine to crash out with an error.
Discord has started sending some maps with integer keys for interactions payloads. We previously handled snowflake payloads (although these payloads used string keys anyway).
This PR:
- Checks whether `Nostrum.Util.maybe_to_atom/1` is receiving an integer, if so, just return that integer.
- Extend the existing snowflake casting check to include 0, that way we return maps that are indexed with `0` instead of `:"0"` (cursed!)
=> Don't attempt to convert integers to atoms in map casting

lib/nostrum/shard/event.ex
Log the shard that we are resuming on both on disconnection and on
reconnection. Additionally, clarify the documentation that we are
jittering the heartbeat, not the HELLO or other payloads.
=> Improve messages on shard resume

lib/nostrum/constants.ex, lib/nostrum/struct/guild/member.ex, lib/nostrum/struct/guild/member/flags.ex, test/nostrum/struct/guild/member/flags_test.exs
Add some fields that we have missed over recent API changes to the member object.
- `flags`: Flags related to membership screening
- `avatar` and `avatar_url/3` bring support for custom guild avatars
- `pending` is also related to membership screening
=> Add missing fields from member API object

guides/functionality/state.md
Updates state docs with the previously agreed upon QLC examples in issue
Additionally, provides an example of how to evaluate a QLC query and
return the result to use within Elixir.
Closes #552
=> Update state docs with new QLC examples

lib/nostrum/shard/event.ex
Per [1] and [2], if the `d` field is set to `true` we may attempt to
resume again with the same session, otherwise we should not. nostrum
would previously loop on trying to resume on the same session after an
invalid session was sent, and the behaviour of simply sending an
identify payload did not work as expected. When the session that we try
to resume with is invalid, perform a reconnect and do the whole
handshake, greeting and meeting the parents thing all over again.
[1]: https://discord.com/developers/docs/topics/gateway-events#invalid-session
[2]: https://discord.com/developers/docs/topics/gateway#resuming
=> Only attempt resume if the gateway says we can

lib/nostrum/struct/user.ex, lib/nostrum/struct/user/flags.ex, test/nostrum/cache/user_cache_meta_test.exs
- Do not automatically parse user public flags
- Remove OAuth2-only user attributes
=> Implement memory optimizations in user struct

examples/event_consumer.ex
`use Nostrum.Consumer` adds this automatically these days.
=> Remove obsolete handle_event clause from example consumer

.github/workflows/docs.yml, .github/workflows/test_and_lint.yml
Updates GitHub Action versions to latest versions of available actions.
Prevents a spam of 15+ warnings in CI about deprecated node.js versions.
=> Update GitHub Action versions

lib/nostrum/shard/session.ex
Make logs such as this:
[info] Asked to reconnect with session SESSION
[info] Re-established websocket connection
[info] Resuming on shard session SESSION
[info] Asked to reconnect with session SESSION
[info] Re-established websocket connection
[info] Resuming on shard session SESSION
Less confusing by ensuring the user knows we successfully resumed.
=> Log at INFO level when shard connection is up

guides/cheat-sheets/api.cheatmd, guides/cheat-sheets/qlc.cheatmd, mix.exs
Introduces new cheat sheets to the documentation using the ExDoc `.cheatmd` functionality.
I'll attach screenshots in the comments of this PR shortly.
This adds a new group for cheat sheets on the `Pages` section of our documentation. See the original issue #553 for a full list of planned sheets.
Closes #553.
=> Add cheat sheets

appup.ex, lib/nostrum/struct/guild/member.ex, lib/nostrum/struct/guild/member/flags.ex, mix.exs
This should be rebased when merged, the last commit on this PR will be the HEAD for 0.9.1.
- Bump version in mix.exs
- Update appup configuration
- Add since tags to new fields from #573
=> Version 0.9.1 Preparation

lib/nostrum/util.ex
Users have reported a state machine error caused by what looks to be the
guild upsert process calling the `Nostrum.Util.maybe_to_datetime`
function on a value that is already a datetime.
We can resolve this by just returning datetimes as is from that function
if we are passed one as an argument.
=> Fix the error caused by trying to cast a datetime to datetime

lib/nostrum/shard/session.ex
Due to how zlib and the state machine work, when the state machine
crashed with an error, it would log the last blob that was received.
This blob could not be decoded from error traces because it depends on
the context that it was received by, additionally we cannot decode it as
an error logging step as once it has been decoded by a context it cannot
be inflated again.
Removing this blob is the best solution here as it shrinks the size of
state machine errors and makes them easier to read by users and Nostrum
team.
In state machine traces, the payload will now be shown as "PAYLOAD
REMOVED", if the last event was not a payload, the event will remain
unmodified.
=> Remove blob of zlib data from state machine errors

lib/nostrum/constants.ex, lib/nostrum/struct/guild.ex, lib/nostrum/struct/guild/system_channel_flags.ex, test/nostrum/struct/guild/system_channel_flags_test.exs
Adds a heap of guild attributes upstream from Discord that we had not yet added to the guild struct.
Details of new attributes are contained within the added typedocs in the changelog, for brevity I will not list them again here.
=> Add new guild attributes

lib/nostrum/api.ex
This PR renames the `options` arg in `create_interaction_response()/3` to `response` to match the docs and other `create_interaction_response` functions.
Right now, the docs read:
This threw me off at first as a Discord API noob.
Nostrum rules, thank you for the great software!
=> Fix Doc Arg Mismatch: Rename "options" to "response"

lib/nostrum/struct/event/ready.ex
Adds the requested resume gateway URL to the Ready struct for debugging purposes.
=> Add resume_gateway_url to Nostrum.Struct.Event.Ready

guides/intro/intro.md, lib/nostrum/shard.ex, lib/nostrum/shard/session.ex, lib/nostrum/shard/supervisor.ex, lib/nostrum/util.ex
This PR provides the user with functions to connect/reconnect/disconnect to the gateway.
In our use case, this allows for zero downtime updates.
This would also advance Issue #542.
```elixir
Nostrum.Shard.Supervisor.connect(0,1) 
info = Nostrum.Shard.Supervisor.disconnect(0)
Nostrum.Shard.Supervisor.reconnect(info)
```
=> feat(shard): manually shard connect and reconnect

lib/nostrum/api/base.ex, lib/nostrum/api/ratelimiter.ex, lib/nostrum/application.ex
=> Remove Application.get_env call from Nostrum.Api.Base

lib/nostrum/shard/session.ex
Occasionally when my bot has to reconnect I would see 2 ready events in quick succession. I noticed from the below stacktrace that the PIDs for the gun connections didn't match and that caused the Shard to blow up.
<details>
<summary>
Stacktrace
</summary>
```erlang
2024-06-23 14:07:30.419 pid=<0.2610.0> [error] ** State machine <0.2610.0> terminating
** Last event = {info,{gun_down,<0.563597.0>,ws,normal,
[#Ref<0.1002467860.1931214849.138526>]}}
** When server state  = {connected,#{stream =>
#Ref<0.1002467860.1931214849.143966>,
seq => 30,
'__struct__' =>
'Elixir.Nostrum.Struct.WSState',
session =>
<<"e7c5b7a3c54504b725b76c1ffa68496a">>,
conn => <0.564181.0>,
gateway =>
<<"gateway-us-east1-d.discord.gg">>,
resume_gateway =>
<<"wss://gateway-us-east1-d.discord.gg">>,
shard_num => …
```
=> Handle case of non matching gun conn pids when receiving a gun_down message

lib/nostrum/cache/member_cache/ets.ex, lib/nostrum/cache/member_cache/mnesia.ex, lib/nostrum/cache/user_cache/ets.ex, lib/nostrum/cache/user_cache/mnesia.ex, lib/nostrum/struct/guild/member.ex, lib/nostrum/struct/user.ex, test/nostrum/cache/user_cache_meta_test.exs
Discovered that the user cache did not always have a properly casted user struct after an update, this fixes that as well as makes it so that updated maps are merged in a way where missing values don't replace existing ones with `nil`
=> Ensure user struct is casted properly before updating ets cache

lib/nostrum/consumer.ex
This would make it so that if a Consumer event crashes for any reason, it by default does not risk bringing down the entire bot but we still log the error.
I got caught by this because for some strange reason Discord was sending message edit events for users who weren't even in the server anymore....
=> Proposal: Allow consumers to follow "let it crash" methodology

lib/nostrum/struct/component/role_select.ex, lib/nostrum/struct/component/user_select.ex
It looks like this was just overlooked when copy/pasting the `MentionableSelect` module.
=> Rename `RoleSelect` and `UserSelect` Functions to Match Module Name

lib/nostrum/voice/payload.ex, lib/nostrum/voice/ports.ex
Newest versions of `yt-dlp` print out a deprecation warning for Python versions less than 3.9 regardless of the `-q --no-warnings` options. This causes the first output to be non-audio and ffmpeg won't transcode anything from yt-dlp. 
Removing `:stderr_to_stdout` from erlang ports. This means any stderr will be printed to the console but will fix issues encountered when using newer yt-dlp versions with old python.
=> Stop sending port stderr to stdout
